version: '3'

tasks:
  default:
  clean:
    cmds:
      - rm -r build
  createbuild:
    cmds:
      - mkdir -p build
  build:
    deps: [createbuild]
    cmds:
      - go vet ./...
      - go build -o build/ ./main.go
  test:
    cmds:
      - go test ./...
  test:coverage:
    deps: [createbuild]
    cmds:
      - go test -coverprofile="build/cover.out" ./...
  coverage:
    deps: [test:coverage]
    cmds:
      - go tool cover -html="build/cover.out" -o "build/cover.html"
  coverage:show:
    deps: [test:coverage]
    cmds:
      - go tool cover -html="build/cover.out"
